apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: databases
  namespace: argocd
spec:
  description: Projeto de bancos de dados gerenciado pelo ArgoCD
  sourceRepos:
    - 'git@github.com:davidcardoso-homelab/databases.git'
    - 'https://charts.bitnami.com/bitnami'
  destinations:
    - namespace: databases
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
